<!-- Page d'accueil -->
<h2 class='phrase1'> Ton 1er blog sur la sneakers</h2>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati officia eius molestias sit amet numquam debitis doloremque nulla commodi quia, qui accusantium quis voluptas voluptate nostrum possimus aperiam, similique autem!</p>

<!-- Liste des articles du blog -->
<ul class="post-list">
    <?php foreach($posts as $post): ?>
        <li class="post">
            <h3>
                <i class="fa fa-hand-o-right"></i>&nbsp;
                <!-- Lien vers article de blog détaillé avec les commentaires -->
                <a href="show_post.php?id=<?= intval($post['Id']) ?>" title="Consulter l'article">
                    <?= htmlspecialchars($post['Title']) ?>
                </a>
            </h3>
            <!-- Seul un extrait de l'article du blog est affiché -->
            <article><?= substr(htmlspecialchars($post['Contents']), 0, 100) ?>&nbsp;[...]</article>
            <small>
                Rédigé par <?= htmlspecialchars($post['FirstName']) ?> <?= htmlspecialchars($post['LastName']) ?>
                le <?= htmlspecialchars($post['CreationTimestamp']) ?>
            </small>
        </li>
    <?php endforeach; ?>
</ul>